#spring boot
spring.datasource.url: jdbc:mysql://47.98.132.196:3306/vueblog
spring.datasource.username: root
spring.datasource.password: anjie123B
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
mybatis.config-location: classpath:/mybatis-config.xml
logging.level.org.springframework.security: info